<?php
$page_title = "Manage Automated Backups";
require_once '../../config.php';
require_once '../../functions.php';

check_role('superadmin');

$errors = [];
$backup_path = BACKUP_PATH;

// Ensure backup directory exists
if (!is_dir($backup_path)) {
    mkdir($backup_path, 0755, true);
}

// --- ACTION HANDLER ---

// Handle Deletion
if (isset($_GET['action']) && $_GET['action'] == 'delete' && isset($_GET['file'])) {
    $file_to_delete = basename($_GET['file']); // Sanitize to prevent directory traversal
    $file_path = $backup_path . $file_to_delete;

    if (file_exists($file_path)) {
        if (unlink($file_path)) {
            $_SESSION['success_message'] = "Backup file '{$file_to_delete}' deleted successfully.";
        } else {
            $_SESSION['error_message'] = "Could not delete the file. Please check permissions.";
        }
    } else {
        $_SESSION['error_message'] = "File not found.";
    }
    redirect('manage_automated.php');
}

// Handle Download
if (isset($_GET['action']) && $_GET['action'] == 'download' && isset($_GET['file'])) {
    $file_to_download = basename($_GET['file']);
    $file_path = $backup_path . $file_to_download;

    if (file_exists($file_path)) {
        header('Content-Description: File Transfer');
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $file_to_download . '"');
        header('Expires: 0');
        header('Cache-Control: must-revalidate');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file_path));
        readfile($file_path);
        exit;
    } else {
        $_SESSION['error_message'] = "File not found for download.";
        redirect('manage_automated.php');
    }
}

// Handle Restore
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['restore_backup'])) {
    $file_to_restore = basename($_POST['restore_file']);
    $confirmation_text = trim($_POST['confirmation_text'] ?? '');

    if ($confirmation_text !== 'I understand this is irreversible') {
        $errors[] = "Confirmation text is incorrect. Please type the phrase exactly as shown.";
    }

    $file_path = $backup_path . $file_to_restore;
    if (!file_exists($file_path)) {
        $errors[] = "The selected backup file no longer exists on the server.";
    }

    if (empty($errors)) {
        $sql_content = file_get_contents($file_path);
        if ($sql_content === false) {
            $errors[] = "Could not read the backup file.";
        } else {
            try {
                $db->exec("SET FOREIGN_KEY_CHECKS=0;");
                $db->exec($sql_content);
                $db->exec("SET FOREIGN_KEY_CHECKS=1;");
                $_SESSION['success_message'] = "Database restored successfully from '{$file_to_restore}'!";
                redirect('manage_automated.php');
            } catch (PDOException $e) {
                $db->exec("SET FOREIGN_KEY_CHECKS=1;");
                $errors[] = "A critical error occurred during restore: " . $e->getMessage();
            }
        }
    }
}

// --- DATA FETCHING ---
$backup_files = [];
$files = array_diff(scandir($backup_path), array('.', '..'));
foreach ($files as $file) {
    if (pathinfo($file, PATHINFO_EXTENSION) == 'sql') {
        $file_path = $backup_path . $file;
        $backup_files[] = [
            'name' => $file,
            'size' => filesize($file_path),
            'date' => filemtime($file_path)
        ];
    }
}
// Sort files by date, newest first
usort($backup_files, fn($a, $b) => $b['date'] <=> $a['date']);

require_once '../../header.php';
?>

<?php require_once '../sidebar_superadmin.php'; ?>
<?php require_once '../../navbar.php'; ?>

<div class="container-fluid px-4">
    <h1 class="mt-4"><?php echo $page_title; ?></h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="../dashboard.php">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="index.php">Backup & Restore</a></li>
        <li class="breadcrumb-item active">Manage Automated Backups</li>
    </ol>

    <?php display_flash_messages(); ?>
    <?php if (!empty($errors)) echo '<div class="alert alert-danger"><ul>' . implode('', array_map(fn($e) => "<li>$e</li>", $errors)) . '</ul></div>'; ?>

    <div class="card mb-4">
        <div class="card-header"><i class="fas fa-archive me-1"></i> Stored Backup Files</div>
        <div class="card-body">
            <p>These backups are automatically generated by the daily scheduled task. You can download them for safekeeping, restore the system to a specific point, or delete old files.</p>
            <div class="table-responsive">
                <table class="table table-bordered table-hover align-middle">
                    <thead>
                        <tr>
                            <th>Filename</th>
                            <th>Date Created</th>
                            <th>File Size</th>
                            <th class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if (empty($backup_files)): ?>
                            <tr><td colspan="4" class="text-center">No automated backup files found.</td></tr>
                        <?php else: foreach ($backup_files as $file): ?>
                        <tr>
                            <td><i class="fas fa-file-alt me-2"></i><?php echo htmlspecialchars($file['name']); ?></td>
                            <td><?php echo date('d M Y, h:i A', $file['date']); ?></td>
                            <td><?php echo round($file['size'] / 1024 / 1024, 2); ?> MB</td>
                            <td class="text-center">
                                <a href="?action=download&file=<?php echo urlencode($file['name']); ?>" class="btn btn-sm btn-primary" title="Download"><i class="fas fa-download"></i></a>
                                <button type="button" class="btn btn-sm btn-warning restore-btn" data-bs-toggle="modal" data-bs-target="#restoreModal" data-filename="<?php echo htmlspecialchars($file['name']); ?>" title="Restore from this backup"><i class="fas fa-history"></i></button>
                                <a href="?action=delete&file=<?php echo urlencode($file['name']); ?>" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to permanently delete this backup file?');" title="Delete"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Restore Modal -->
<div class="modal fade" id="restoreModal" tabindex="-1" aria-labelledby="restoreModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="manage_automated.php" method="POST">
                <div class="modal-header bg-warning">
                    <h5 class="modal-title" id="restoreModalLabel"><i class="fas fa-exclamation-triangle"></i> Confirm Restore</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="restore_file" id="restore_file_input">
                    <p>You are about to restore the database from the backup file: <strong id="restore_filename_display"></strong>.</p>
                    <div class="alert alert-danger">
                        <strong>WARNING:</strong> This action will <strong>completely erase and overwrite</strong> all current data. This is irreversible.
                    </div>
                    <div class="mb-3">
                        <label for="confirmation_text" class="form-label">To confirm, please type: <code class="text-danger">I understand this is irreversible</code></label>
                        <input type="text" name="confirmation_text" id="confirmation_text" class="form-control" autocomplete="off" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" name="restore_backup" class="btn btn-warning">Restore Now</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require_once '../../footer.php'; ?>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const restoreModal = document.getElementById('restoreModal');
    restoreModal.addEventListener('show.bs.modal', function (event) {
        const button = event.relatedTarget;
        const filename = button.getAttribute('data-filename');
        
        const modal = this;
        modal.querySelector('#restore_file_input').value = filename;
        modal.querySelector('#restore_filename_display').textContent = filename;
        modal.querySelector('#confirmation_text').value = ''; // Clear on open
    });
});
</script>